spring.application.name=RealTimeAlertingService

spring.datasource.username = ${DB_USERNAME}
spring.datasource.url = jdbc:postgresql://localhost:5432/realtime_alerting_service
spring.datasource.password = ${DB_PASSWORD}

spring.datasource.driver-class-name = org.postgresql.Driver
spring.jpa.show-sql = true
spring.liquibase.change-log = classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled = true
spring.jpa.hibernate.ddl-auto= none

logging.level.root=INFO
logging.level.com.example.project=DEBUG

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n



